name = "FlareNet"
author = "PenguinTijn"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e4554187b58c62179fa8a179525d0c7cca827e9cf889ddef50b3a34f32959f2"

[versions]
forge = "47.2.17"
minecraft = "1.20.1"
