name = "FlareNet"
author = "PenguinTijn"
version = "0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e3220767d2b53398dd91ecedd48a6e4e35fcfcf5b1fd397f45fc09a7b8b3236f"

[versions]
forge = "47.2.17"
minecraft = "1.20.1"
