name = "FlareNet"
author = "PenguinTijn"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "55e008e26b03a30cbf9d9f60fdf1e93d2f10771ce91ff1372d82f9c962334250"

[versions]
forge = "47.2.17"
minecraft = "1.20.1"
