name = "FlareNet"
author = "PenguinTijn"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93f28cb0e2dc27d527b1b036ce052968555f0e95742b08d8a03f6d2a250114fd"

[versions]
forge = "47.2.17"
minecraft = "1.20.1"
