name = "FlareNet"
author = "PenguinTijn"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d366a8843462c20af51d438c5b32df37836353cf9a4aa62fd1d0ec8c5d66076a"

[versions]
forge = "47.2.17"
minecraft = "1.20.1"
