name = "FlareNet"
author = "PenguinTijn"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3f6499cb3e2b32823a982f1d44708f9bd8b5b0d0627819cd9d19df65af58ce29"

[versions]
forge = "47.2.17"
minecraft = "1.20.1"
