name = "FlareNet"
author = "PenguinTijn"
version = "0.0.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3944bf51e71d98afffc742539fc55c716b8ee8f0100a7759f63dc023c69b90e4"

[versions]
forge = "47.2.17"
minecraft = "1.20.1"
