name = "FlareNet"
author = "PenguinTijn"
version = "0.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c122ccc706618c31869fa34c664310e9101caa1cd6d70a364927fd20d331bc17"

[versions]
forge = "47.2.17"
minecraft = "1.20.1"
