name = "FlareNet"
author = "PenguinTijn"
version = "0.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bff3602ec9d4db321ff8c3eb739de15a47e6ac395755734395cbb5667bdd66a2"

[versions]
forge = "47.2.17"
minecraft = "1.20.1"
