name = "FlareNet"
author = "PenguinTijn"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c8c5190dd90dce383b855858ad091ee565d1f7082cdd7deb694c53a38ae7d371"

[versions]
forge = "47.2.30"
minecraft = "1.20.1"
