name = "FlareNet"
author = "PenguinTijn"
version = "0.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e05924c0a0833775c0702cc02394a78fa6b7b5430c6eeac1477869b5e88129d0"

[versions]
forge = "47.2.17"
minecraft = "1.20.1"
